### ISSUE TITLE
Identify how we will collaborate

### ISSUE THREAD

**Issue by rakshithv** [Scarabyte/SSW690-Project#12]
Add a new slide, to address item 5 from the assignment
Identify how and when your team will interact and work together, e.g. will you meet in person on Monday evening at 8:00 PM or will you meet online with Slack, Google Hangouts, etc.?

**Comment by Scarabyte** [comment]
Let's discuss this today and agree on meeting times and communication tools.

**Comment by Scarabyte** [comment]
Agreement from 20180830 meeting:
* Regular team meetings on Thursdays 7:00 - 9:00 PM Eastern
* Shorter "stand-up" meetings on Sundays 7:00 - 7:30 PM Eastern

Meeting room: Google Meet room provided by Prof. Rowland
Whatsapp for messaging in between meetings

**Comment by Scarabyte** [comment]
Resolved in commit f92abfa9486cf07004010b91fed0461e805f9f90
