### ISSUE TITLE
Initial Environment Set up:

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#13]
Each team member will Install and configure Android development Studio with OpenCV Library

**Comment by Scarabyte** [comment]
Follow the tutorial at https://developer.android.com/training/basics/firstapp/ to create a sample app.

**Comment by bsapana** [comment]
I have uploaded OpenCV project in sb_opencv branch. To execute the sample from this project please follow below steps.

1) Download Android Studio from here..
https://developer.android.com/studio/

You can use Eclipse IDE as well but then you'll have to install ADT and CDT plugins for Eclipse

2)To download OpenCV Andoid Library on Android Studio, follow steps provided at below loacation..

https://android.jlelse.eu/a-beginners-guide-to-setting-up-opencv-android-library-on-android-studio-19794e220f3c

 Step 1: I have downloaded the latest version of library 3.4.3

 Step 7: add the camera permissions outside of <application> tag in AndroidManifest.xml file.

Step 8: To try out sample app, You will have to select deployment target (window pops up when you run the application). It can be your physical device or 'create new virtual device. I connected my S6 phone via USB. It was not detecting until I downloaded usb driver on my laptop. 

Also, activate developer options on your phone. Instructions are here for S6 https://android.stackexchange.com/questions/124917/where-is-the-developer-options-in-the-settings-on-the-s6

Enable USB debugging on Andoid:
https://www.phonearena.com/news/How-to-enable-USB-debugging-on-Android_id53909

Step 9: Please readme to select right architecture for your device. I installed file ending _ameabi-v7a

Step 10: Whatever the project name you selected, that name app will get created on your device. Give the permission to camera. To do so..
From a Home screen, navigate: Apps icon > Settings > Apps > Application manager.
Tap the appropriate app.
If available, tap Permissions.
Tap Camera to turn on or off 

To test I created an oval, circle and filled with differnt colors in desktop paint app like below and held my app infornt of it. When I touch the circle or oval using app, it is recognizing correct color. Recognized color displays as strip at upper left corner.

![image](https://user-images.githubusercontent.com/14364300/45255006-48cd4300-b34f-11e8-9c07-760a8787fd03.png)

Hope this helps!

**Comment by Scarabyte** [comment]
Make sure you set the "Camera" permission in your phone's App Settings (Step 10 in Sapana's instructions above). Other than that, I was able to directly download and run the app from the sb_opencv branch.

**Comment by rakshithv** [comment]
Was able to run Sapana's application using the virtual phone
