### ISSUE TITLE
Audible warning of lane departure

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#14]
As a driver, I want the system to audibly notify me when my vehicle departs the lane.

**Comment by kroseberry13SIT** [comment]
Should be relatively simple to develop this - starting with a single annoying tone  and evolving to a spoken warning would be good.

**Comment by kroseberry13SIT** [comment]
Simple method for notification sound: https://looksok.wordpress.com/2013/03/09/android-play-default-notification-sound/

**Comment by Scarabyte** [comment]
Addressed in Pull Request #78
