### ISSUE TITLE
Add filter on image to remove noise

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#16]

**Comment by bsapana** [comment]
**Some Notes:**
There are three filters used for noise removal.
Normalized box filter, Gaussian filter, and Bilateral filter.

It seems like choosing the bilateral filter when the situation demands noise reduction while maximally preserving edges and peaks. If we need to just preserve the peaks and are not bothered by the effect on edge, using gaussian filter with appropriate spatial standard deviation would be more than enough as it is computationally cheaper than bilateral filter. If we neither care about peaks not about edges and simply need to reduce noise, using normalized box filter with appropriate kernel size would do. For optimum computational cost, using kernel size less than or equal to 7 for any algorithm is recommended.

**Comment by kroseberry13SIT** [comment]
This brings up the possibility of having tunable software - being able to select the filters used and to adjust the parameters of those filters at run time would be nice.

**Comment by Scarabyte** [comment]
Filter selection is addressed in #38

**Comment by rakshithv** [comment]
Keith added this functionality in the baseline code. The commit onto the master branch was done in commit b428e53
