### ISSUE TITLE
Identify Road features

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#17]
Need to list all road markings/features to focus on camera image.

**Comment by bsapana** [comment]
Some features which need to be considered as part of input image/video..

Dotted line - can be in yellow or white color
Solid line - can be in yellow or white color
Road Horizon or Vanishing Point

**Comment by Scarabyte** [comment]
Also there could be either a single or a double line...
But we might be able to crop the image so we don't need to look all the way to the horizon, we're mostly interested in the lane right in front of us.

**Comment by kroseberry13SIT** [comment]
Found this while perusing the OpenCV documentation:

https://docs.opencv.org/3.4.3/db/d73/classcv_1_1LineSegmentDetector.html

The LineSegmentDetector class analyzes an image and returns an array of vectors (lines) detected in the image. Will this work for us? What about the distortion created by the camera lens?

**Comment by Scarabyte** [comment]
Simplification: consider only a single-lane road initially. We can add multiple-lane roads later once we get that working.

**Comment by bsapana** [comment]
Some OpenCV functions may be useful while implementing this story.

cv2.inRange() for color selection
cv2.fillPoly() for regions selection
cv2.line() to draw lines on an image given endpoints
cv2.addWeighted() to coadd / overlay two images cv2.cvtColor() to grayscale or change color cv2.imwrite() to output images to file
cv2.bitwise_and() to apply a mask to an image

**Comment by Scarabyte** [comment]
Just leaving this here for reference, from Keith's Week 5 status update:
  * Sequence for lane detection methods:
    1. Correct image distortion with calibration data (requires calibration function to have completed). [Issue #42 and #45]
    2. Apply a region of interest and transform to 'sky view'. [Issue #17 and #46]
    3. Filter the image to find the lane markers.
    4. Fit curves to both left and right side lane markers. [Issue #47]
    5. Project back onto the original image for display. [Issue #48 and #49]

**Comment by Scarabyte** [comment]
All issues in this epic are now complete.
