### ISSUE TITLE
Perform grey scale conversion on an image

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#19]
To facilitate image processing, convert to gray scale. Apply Gaussian filter.

**Comment by Scarabyte** [comment]
Should the "Gaussian filter" part be a separate issue? And would that be part of #16?

**Comment by bsapana** [comment]
This seems like duplicate of #16.

**Comment by kroseberry13SIT** [comment]
This is really, really simple. The processing function is given a frame to work with - calling .gray() on that frame object will return a gray scale image of that frame. This can get more complicated if we need to adjust the method by which the image is converted to gray scale.

**Comment by rakshithv** [comment]
Keith added this functionality into the baseline code. This code was added to the master branch in commit b428e53
