### ISSUE TITLE
Perform Hough transformation on an image

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#20]
Implement the [Hough transform](https://en.wikipedia.org/wiki/Hough_transform) used by the LDWS.

**Comment by kroseberry13SIT** [comment]
This is a single call to the OpenCV library (HoughLines), which takes as input the original image and produces as output the transformed image. The work will be in tuning the parameters to the function.

**Comment by Scarabyte** [comment]
A first draft of this is uploaded in commit 782c728aec4f8cdc1b6ba134bd306171dae7100a but I'm not sure if it's quite working properly because I don't see the red lines overlaid on the camera image that I was expecting to. Perhaps some of the thresholds and parameters might need to be adjusted?

**Comment by Scarabyte** [comment]
Merged into master branch in commit 023f682ccc1330155834d0d5fbf87c24375590a2 which improves the image processing method.
