### ISSUE TITLE
Perform Canny Edge detection

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#21]
Implement the [Canny edge detector](https://en.wikipedia.org/wiki/Canny_edge_detector) used by the LDWS.

**Comment by kroseberry13SIT** [comment]
This is a single function call to the OpenCV library (Canny), which takes as input the original image and produces as output an image in which the edges are clearly identified. The function call itself is not difficult; the work will be in tuning the parameters supplied to the function.

**Comment by kroseberry13SIT** [comment]
Added canny edge detection to the 21_canny branch.
