### ISSUE TITLE
Identify lane edges

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#22]
From a processed image, determine the edges of the road lanes.

**Comment by Scarabyte** [comment]
Is this a duplicate of #21? I'm not sure what I was thinking when I opened it, but it may have been that one issue would implement the algorithm itself, and then the other would implement an app-level function that uses it. However, if the algorithm is provided by the OpenCV library, then perhaps we don't need two separate issues.

**Comment by kroseberry13SIT** [comment]
This isn't a duplicate, in my interpretation. This task is to take the filtered image and any attributes of that image, and determine where the "travel lane" really is. I believe this will be a big task.

**Comment by kroseberry13SIT** [comment]
Okay, I now think this is a duplicate of #17, Identify Road Features. Suggest closing one of these.

**Comment by Scarabyte** [comment]
Close as duplicate of #17
