### ISSUE TITLE
Visual Indication that system is operational

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#27]
As a user, I want the application to visually inform me that it is operating and that I'm traveling in the lane

Developer's Note: Normal operation here - show some visual indicator that the system is operational and the vehicle is in a good vector with respect to the travel lane.

**Comment by Scarabyte** [comment]
Is the "app is operational" indication something different from just having the video feed on-screen?
For the "travelling in the lane" part, do we envision something like the green/yellow/red markings on some backup cameras?

**Comment by kroseberry13SIT** [comment]
This is a user story and could be broken down into individual tasks, which will then get implemented in sprints. I agree that displaying the video on the screen could be in the first sprint, whereas the display of the travel lane (where the lane edges are annotated/highlighted) would be in a later sprint - much later.

So let's split this one up.

**Comment by Scarabyte** [comment]
This user story is simplified to handle only Item 1 above as follows:

_As a user, I want the application to visually inform me that it is operating
Developer's Note: Normal operation here - show some visual indicator that the system is operational_

As of the end of Sprint 1 (commit 023f682ccc1330155834d0d5fbf87c24375590a2), the app does show the video with identified lines highlighted, so Item 1 is complete.
Item 2 will be addressed in a later sprint, as mentioned above.
