### ISSUE TITLE
Calibrate the Camera

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#42]
All cameras have distortion that must be corrected so that features in the image may be accurately detected and recognized. This item is to perform camera calibration in the BackSeatDriver application. This is a part of lane detection.

**Comment by bsapana** [comment]
Looks like we can use openCV package calib3d.Calib3d and methods related to chessboardcorners.

**Comment by Scarabyte** [comment]
Implemented in Pull Request #52 
Use the 11x4 OpenCV asymmetric circles grid for the calibration pattern.
https://source.android.com/compatibility/cts/images/acircles_pattern.pdf
