### ISSUE TITLE
Correct image distortion

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#45]
Using the calibration data, correct the image distortion of the video feed.

**Comment by bsapana** [comment]
Variations of this function is available in opencv
public static void fisheye_undistortImage(Mat distorted, Mat undistorted, Mat K, Mat D);

public static void fisheye_undistortPoints(Mat distorted, Mat undistorted, Mat K, Mat D);

**Comment by Scarabyte** [comment]
Resolved in Pull Request #55
