### ISSUE TITLE
Transform image to 'sky view'

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#46]
The sky view is necessary to detect the lane markings and fit curves to them.

**Comment by bsapana** [comment]
I think we have to fix image distortion before applying sky view that means it's blocked by #45

**Comment by Scarabyte** [comment]
Also called Bird's Eye view - see the example in the OpenCV textbook.

**Comment by Scarabyte** [comment]
It seems there are several steps involved in this transformation. From the Learning OpenCV textbook:
1. Read the intrinsics and distortion models for the camera.
2. Find a known object on the ground plane. Get at least four points at subpixel accuracy.
3. Enter the found points into cv::getPerspectiveTransform() to compute the homography matrix H for the ground plane view.
4. Use cv::warpPerspective() with the flags cv::WARP_INVERSE_MAP | cv::INTER_LINEAR to obtain a frontal parallel (bird’s-eye) view of the ground plane.

Also see https://nikolasent.github.io/opencv/2017/05/07/Bird's-Eye-View-Transformation.html which has a slightly different (possibly simpler?) approach.

**Comment by Scarabyte** [comment]
This has some examples that seem like they might be useful: https://www.programcreek.com/java-api-examples/?class=org.opencv.core.Core&method=perspectiveTransform
I've also been reading the textbook, Chapter 11 (especially the Perspective Transformation section, around p.339 in the PDF).

**Comment by Scarabyte** [comment]
Marking resolved as of Pull Request #60. The Fit Curves task (Issue #47) will modify the code as needed from there.
