### ISSUE TITLE
Dashed lane lines are not detected as a lane marking

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#65]
If the image has dashed lines with longer gaps, current detect function is not detecting it as a lane line. Try this with single_lane_3.jpg or multi_lane_1.jpg located in resources folder.  We may try this with both white and yellow lines.

**Comment by Scarabyte** [comment]
Updated in commit f26f470efd00860987fc30385882bf1903d7fd5d for the Canny Edge and Hough Lines transforms, however @kroseberry13SIT 's updates for Issue #47 comment those lines out and use a different method instead. The changes are merged in Pull Request #69 just so we don't lose them in case we ever want/need to go back to that method, but there should be no functional impact on the code.

**Comment by Scarabyte** [comment]
Seems to be resolved as part of the updates as of commit 4f17d7d6945947a4f2ba8308713fdaa2023eb880
In any case, the lane detection method has been modified, so this issue seems to be no longer applicable.
