### ISSUE TITLE
Prepare Final Presentation 

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#66]
Get a head start to final presentation 

- We should make sure to cover all the points mentioned in the assignment statement in week 14 module

- Use the outline in Canvas as a guide

Create a google document and start adding content in Spint 4 and Sprint 5

**Comment by rakshithv** [comment]
https://drive.google.com/open?id=1xXkyarXH8TSNJNYXK3AzIxtMn0gClhUDANSGyDQW9tM

The presentation draft is at this location. Will add comments as content is finalized. Currently 0/8 presentation guidelines have been completed

**Comment by Scarabyte** [comment]
Presentation is complete and available in the shared Google Drive folder.
