### ISSUE TITLE
Lane position indication

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#68]
Add an indicator (percent is best) of how far the vehicle is away from the middle of the lane. Example: 13% left of center; 22% right of center.

**Comment by Scarabyte** [comment]
Here's the document that defines the rules for lane markings. Unfortunately the physical width of lanes, as well as the lane markings themselves, can vary depending on the type of road and purpose of the marker.
A percentage is fine, but a physical measurement would be tricky unless there's some reliable reference object we can use.
https://mutcd.fhwa.dot.gov/pdfs/millennium/06.14.01/3ndi.pdf

**Comment by Scarabyte** [comment]
Addressed in Pull Request #77
