### ISSUE TITLE
Sprint 5 testing

### ISSUE THREAD

**Issue by bsapana** [Scarabyte/SSW690-Project#79]
Test the stock images with latest code that includes Sobel algorithm, Sky view and, lane position.

**Comment by Scarabyte** [comment]
Sprint 5 test results on stock images are uploaded in commit 7738a3fa3274bcbf88aeafd52d932b50a5a03fa6

**Comment by bsapana** [comment]
Created separate folder Output_Sprint 5 for processed images (output) in SSW690-Project/docs/Images/.

Testing observations Sprint 5, week 2

Application is detecting lanes more precisely than last Sprint. Other objects detected in old code has been fixed and area is interest is accurately represented.  It seems like white dotted lines are not detected correctly for most images.

test01 - dotted lines and lance area is being detected correctly
single_lane_3 - Issue is with recognizing dotted lines as lanes, edge lines are correctly detected
single_lane_5 - Edges and center lines are detected correctly
single_lane_8 - Center lines detection is now good
treeshadow -  center and edges are detected
treeshadow1 - Edge is detected however because of shadow it shows that center is misplaced.
multilane1 - No lines detected.
cloud_hills1 -  Even in cloudy weather I see app is detecting center and edge lines. 
four_lane_1 - No lanes detected. 
rain - Quality of image itself is not that good, still it's detecting broken right lane and center lane
